CREATE TABLE IF NOT EXISTS notification_preferences (
  actor_id INTEGER PRIMARY KEY REFERENCES actors(id) ON DELETE CASCADE,
  likes BOOLEAN NOT NULL DEFAULT TRUE,
  replies BOOLEAN NOT NULL DEFAULT TRUE,
  mentions BOOLEAN NOT NULL DEFAULT TRUE,
  boosts BOOLEAN NOT NULL DEFAULT TRUE,
  follows BOOLEAN NOT NULL DEFAULT TRUE
);
